import Head from 'next/head'
import { useEffect } from 'react'
import styles from '../styles/Home.module.scss'

export default function Home() {

  useEffect(function () {
    if (localStorage.getItem('user')) {
      window.location.replace('/update-user');
    } else {
      window.location.replace('/login');
    }
  },[])

  return (
    <div className={styles.container}>
      <Head>
        <title>SimInteligência Challenge</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  )
}
